Cleanup code, Fix script permissions, Correct envs
LajaSoft/audio-webui-docker pull request #4
Opened 2023-08-13 06:54 UTC by sammcj

- fix broken shell script file permissions
- add missing shebang to shell script
- make use of the existing .env file and defaults
- add gitignore for volumes suggested in docker-compose
- correct entrypoint script from using . within a shell script (does not always work) to eval

2023-08-14 13:40 UTC, zba requested changes

2023-08-14 13:40 UTC, zba commented on Dockerfile
> +    && unzip audio-webui.zip \
I not like combine, because when need to update last command you need to run it again, I understand that it makes overhead on each command by disk space, but this is small and I prefer faster changes. If you like you can do second stage build which wil be single diff with base image and better for clusters anyway , also I though to remove wget here and replace it with clone, because I don;t think running installer is god idea and will require maintanance later :)

2023-08-14 13:40 UTC, zba commented on run.sh
> +eval /app/.env
why not ```source``` ? what wrong with ```.``` ?

2023-08-14 13:40 UTC, zba commented on run.sh
> +eval venv/bin/activate
same

2023-08-14 13:40 UTC, zba commented on Dockerfile
> +ENTRYPOINT [ "/app/run.sh" ]
I not like ENTRYPOINT here, same with EXPOSE, my system is docker compose and I not want to make side effects for keeping raw Dockerfile compatibility.

2023-08-14 13:40 UTC, zba commented on docker-compose.yml
> -    command: "/app/run.sh"
I like command, I though to add args here and proxy it to app runner,

2023-08-14 13:40 UTC, zba commented on .gitignore
💖💖💖💖

2023-08-14 13:40 UTC, zba commented on Dockerfile
> +    && rm -rf /var/lib/apt/lists/*
not got this, why you need apt lists during install setuptools ?

2024-02-01 18:43 UTC, Collected5353 commented
Is there a reason to use Venv on the docker image? I just ran /bin/app/run.sh, and it started installing everything.

2024-02-01 18:47 UTC, zba commented
> Is there a reason to use Venv on the docker image? I just ran /bin/app/run.sh, and it started installing everything.

there was some tricky installation process with thiss install.py and system for dependencies I din't knew, I just pack same as in their readme, I even downloaded installer which does ```git clone``` :)

2024-02-01 19:12 UTC, Collected5353 commented
Let me test again. When I run it fresh, something is happening to the .env. It's not getting copied right. 
`    : No such file or directory1: /app/.env
: No such file or directory3: venv/bin/activate:
`
This is from an ls from exec:
`# ls
 CONTRIBUTING.md     assets                    example_semantic_gens.py   installers   run.bat          scripts       update.sh
 LICENSE             audio_webui_colab.ipynb   extensions                 main.py      run.sh           setup_tools   venv
 activate_only.bat   autodebug                 hubert                     readme       run_py.bat       simplestyle  'venv'$'\r'
 activate_only.sh    data                      install.py                 readme.md    run_python.bat   update.bat    webui
# ` See the venv$?

2024-02-01 19:21 UTC, Collected5353 commented
You know what? It's probably because I am using docker on windows....

2024-02-01 19:46 UTC, zba commented
> No such file or directory3: venv/bin/activate

this command shall create venv/bin/activate
`python3 -m venv venv `


may be yes, on windows I using wsl2 (and alsways run docker from inside it) and it is same for me on windows as on linux :)

2024-03-17 10:26 UTC, closed without merging